# -*- coding: utf-8 -*-
"""ДЗ2_Тоболовська Євгенія.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K1I1Xne2dpcPUF0ELemLfoO-4YOTwCyL

Завдання 1
"""

import queue
import random
import time

def generate_request(q):
    request_id = random.randint(1000, 9999)  # Генеруємо унікальний ID заявки
    print(f"Генеруємо заявку з ID: {request_id}")
    q.put(request_id)

def process_request(q):
    if not q.empty():
        request_id = q.get()
        print(f"Обробляємо заявку з ID: {request_id}")
    else:
        print("Черга пуста, немає заявок для обробки.")

# Створюємо чергу заявок
request_queue = queue.Queue()

# Головний цикл програми
try:
    while True:
        user_input = input("Натисніть Enter для генерації заявки, 'p' для обробки заявки або 'q' для виходу: ")
        if user_input.lower() == 'q':
            print("Вихід з програми.")
            break
        elif user_input.lower() == 'p':
            process_request(request_queue)
        else:
            generate_request(request_queue)

        time.sleep(1)
except KeyboardInterrupt:
    print("\nПрограма була перервана користувачем.")

"""Завдання 2"""

from collections import deque

def is_palindrome(s):
    # Перетворюємо рядок в нижній регістр та видаляємо пробіли
    formatted_s = ''.join(c.lower() for c in s if c.isalnum())

    # Створюємо двосторонню чергу з символів рядка
    char_deque = deque(formatted_s)

    while len(char_deque) > 1:
        if char_deque.popleft() != char_deque.pop():
            return False

    return True

# Тестування функції
test_strings = ["Racecar", "No lemon, no melon", "Python", "А роза упала на лапу Азора"]
for s in test_strings:
    print(f"'{s}' - це паліндром?" , is_palindrome(s))